import { useEffect, useState } from 'react';
import { Button, Card, Form } from 'react-bootstrap';
import { coachService } from '../../services/coach.service';

const CoachProfileSection = () => {
  const [profile, setProfile] = useState<any>(null);
  const [form, setForm] = useState<any>({ sports: '', specialties: '', teachingModes: ['offline'], area: '', bio: '', pricePerHour: '', sessionDurations: '60' });
  const [message, setMessage] = useState('');
  useEffect(() => { coachService.getMyProfile().then(p => { setProfile(p); if (p) setForm({ sports: (p.sports || []).join(', '), specialties: (p.specialties || []).join(', '), teachingModes: p.teachingModes || ['offline'], area: p.area || '', bio: p.bio || '', pricePerHour: p.pricePerHour || '', sessionDurations: (p.sessionDurations || [60]).join(', ') }); }).catch(() => undefined); }, []);
  const save = async (e: React.FormEvent) => { e.preventDefault(); try { const data = await coachService.saveMyProfile({ sports: form.sports.split(',').map((x: string) => x.trim()).filter(Boolean), specialties: form.specialties.split(',').map((x: string) => x.trim()).filter(Boolean), teachingModes: form.teachingModes, area: form.area, bio: form.bio, pricePerHour: Number(form.pricePerHour), sessionDurations: form.sessionDurations.split(',').map((x: string) => Number(x.trim())).filter(Boolean) }); setProfile(data); setMessage('Đã lưu hồ sơ huấn luyện và gửi Admin duyệt.'); } catch (err: any) { setMessage(err.response?.data?.message || 'Không thể lưu thông tin Coach.'); } };
  const status = profile?.reviewStatus;
  return <Card style={{ borderRadius: '16px', border: '1px solid #e2e8f0', boxShadow: 'none', marginBottom: '24px' }}><Card.Body className="p-4"><div className="d-flex justify-content-between align-items-center mb-3"><div><h6 className="mb-1" style={{ fontWeight: 700 }}>Thông tin huấn luyện viên</h6><small className="text-muted">Phần mở rộng của hồ sơ cá nhân dành cho Coach.</small></div>{status && <span className={`badge ${status === 'APPROVED' ? 'bg-success' : status === 'REJECTED' ? 'bg-danger' : 'bg-warning text-dark'}`}>{status === 'APPROVED' ? 'Đã duyệt' : status === 'REJECTED' ? 'Cần bổ sung' : 'Chờ duyệt'}</span>}</div>{message && <div className="alert alert-info py-2">{message}</div>}{status === 'REJECTED' && profile?.reviewNote && <div className="alert alert-danger py-2">Phản hồi: {profile.reviewNote}</div>}<Form onSubmit={save}><div className="row g-3"><Form.Group className="col-md-6"><Form.Label>Môn thể thao</Form.Label><Form.Control required value={form.sports} onChange={e => setForm({ ...form, sports: e.target.value })} placeholder="Cầu lông, Pickleball" /></Form.Group><Form.Group className="col-md-6"><Form.Label>Chuyên môn</Form.Label><Form.Control value={form.specialties} onChange={e => setForm({ ...form, specialties: e.target.value })} /></Form.Group><Form.Group className="col-md-6"><Form.Label>Giá mỗi giờ</Form.Label><Form.Control required type="number" min="0" value={form.pricePerHour} onChange={e => setForm({ ...form, pricePerHour: e.target.value })} /></Form.Group><Form.Group className="col-md-6"><Form.Label>Thời lượng (phút)</Form.Label><Form.Control required value={form.sessionDurations} onChange={e => setForm({ ...form, sessionDurations: e.target.value })} placeholder="60, 90" /></Form.Group><Form.Group className="col-md-6"><Form.Label>Hình thức</Form.Label><div>{['offline', 'online'].map(mode => <Form.Check inline key={mode} type="checkbox" label={mode === 'offline' ? 'Trực tiếp' : 'Online'} checked={form.teachingModes.includes(mode)} onChange={e => setForm({ ...form, teachingModes: e.target.checked ? [...form.teachingModes, mode] : form.teachingModes.filter((x: string) => x !== mode) })} />)}</div></Form.Group><Form.Group className="col-md-6"><Form.Label>Khu vực dạy trực tiếp</Form.Label><Form.Control value={form.area} onChange={e => setForm({ ...form, area: e.target.value })} /></Form.Group><Form.Group className="col-12"><Form.Label>Giới thiệu</Form.Label><Form.Control as="textarea" rows={3} value={form.bio} onChange={e => setForm({ ...form, bio: e.target.value })} /></Form.Group></div><Button type="submit" variant="success" className="mt-3">Lưu thông tin Coach</Button></Form></Card.Body></Card>;
};

export default CoachProfileSection;
