import { useEffect, useState } from 'react';
import { Button, Card, Container, Form, Spinner, Tab, Nav } from 'react-bootstrap';
import { useNavigate } from 'react-router-dom';
import { coachService } from '../../services/coach.service';
import { ROUTES } from '../../constants';

const DAYS = ['Chủ nhật', 'Thứ hai', 'Thứ ba', 'Thứ tư', 'Thứ năm', 'Thứ sáu', 'Thứ bảy'];

const CoachDashboardPage = () => {
  const navigate = useNavigate(); const [profile, setProfile] = useState<any>(null); const [bookings, setBookings] = useState<any[]>([]); const [availability, setAvailability] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('');
  const load = async () => { try { const [p, b] = await Promise.all([coachService.getMyProfile(), coachService.getMyBookings()]); setProfile(p); setBookings(b); setAvailability(p?.weeklyAvailability || []); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const saveAvailability = async () => { try { const p = await coachService.saveAvailability({ weeklyAvailability: availability, dateExceptions: profile?.dateExceptions || [], isAcceptingBookings: true }); setProfile(p); setMessage('Đã lưu lịch rảnh.'); } catch (err: any) { setMessage(err.response?.data?.message || 'Không thể lưu lịch rảnh.'); } };
  const transition = async (id: string, action: 'confirm' | 'reject' | 'complete') => { const reason = action === 'reject' ? window.prompt('Lý do từ chối:') || undefined : undefined; if (action === 'reject' && !reason) return; try { await coachService.transitionBooking(id, action, reason); load(); } catch (err: any) { setMessage(err.response?.data?.message || 'Không thể cập nhật lịch.'); } };
  if (loading) return <div className="text-center py-5"><Spinner variant="success" /></div>;
  if (!profile || profile.reviewStatus !== 'APPROVED') return <Container className="py-5" style={{ maxWidth: 720 }}><Card><Card.Body className="p-4"><h3>Hồ sơ Coach chưa sẵn sàng</h3><p className="text-muted">Hãy hoàn thiện thông tin huấn luyện trong Hồ sơ cá nhân và chờ Admin duyệt trước khi nhận lịch.</p><Button variant="success" onClick={() => navigate(ROUTES.PROFILE)}>Mở hồ sơ cá nhân</Button></Card.Body></Card></Container>;
  return <Container className="py-4" style={{ maxWidth: 1000 }}><div className="d-flex justify-content-between align-items-center mb-4"><div><h2 className="fw-bold mb-1">Lịch dạy Coach</h2><p className="text-muted mb-0">Quản lý lịch rảnh và các buổi tập đã được đặt.</p></div><Button variant="outline-success" onClick={() => navigate(ROUTES.PROFILE)}>Hồ sơ cá nhân</Button></div>{message && <div className="alert alert-info">{message}</div>}<Tab.Container defaultActiveKey="availability"><Nav variant="tabs" className="mb-3"><Nav.Item><Nav.Link eventKey="availability">Lịch rảnh</Nav.Link></Nav.Item><Nav.Item><Nav.Link eventKey="bookings">Lịch dạy</Nav.Link></Nav.Item></Nav><Tab.Content><Tab.Pane eventKey="availability"><Card><Card.Body>{availability.map((slot, index) => <div className="row g-2 mb-2" key={index}><div className="col-md-4"><Form.Select value={slot.dayOfWeek} onChange={e => setAvailability(availability.map((x, i) => i === index ? { ...x, dayOfWeek: Number(e.target.value) } : x))}>{DAYS.map((day, i) => <option value={i} key={day}>{day}</option>)}</Form.Select></div><div className="col-md-3"><Form.Control type="time" value={slot.startTime} onChange={e => setAvailability(availability.map((x, i) => i === index ? { ...x, startTime: e.target.value } : x))} /></div><div className="col-md-3"><Form.Control type="time" value={slot.endTime} onChange={e => setAvailability(availability.map((x, i) => i === index ? { ...x, endTime: e.target.value } : x))} /></div><div className="col-md-2"><Button variant="outline-danger" onClick={() => setAvailability(availability.filter((_, i) => i !== index))}>Xóa</Button></div></div>)}<Button variant="outline-success" onClick={() => setAvailability([...availability, { dayOfWeek: 1, startTime: '08:00', endTime: '17:00' }])}>Thêm khung giờ</Button><Button className="ms-2" variant="success" onClick={saveAvailability}>Lưu lịch rảnh</Button></Card.Body></Card></Tab.Pane><Tab.Pane eventKey="bookings"><Card><Card.Body>{bookings.length ? bookings.map(booking => <div className="border-bottom py-3 d-flex justify-content-between align-items-center" key={booking._id}><div><strong>{booking.playerId?.fullName || 'Player'}</strong><div className="text-muted small">{new Date(booking.startAt).toLocaleString('vi-VN')} · {booking.sport} · {booking.status}</div></div><div className="d-flex gap-2">{booking.status === 'PENDING_COACH_CONFIRMATION' && <><Button size="sm" variant="success" onClick={() => transition(booking._id, 'confirm')}>Xác nhận</Button><Button size="sm" variant="outline-danger" onClick={() => transition(booking._id, 'reject')}>Từ chối</Button></>}{booking.status === 'CONFIRMED' && new Date(booking.endAt) <= new Date() && <Button size="sm" onClick={() => transition(booking._id, 'complete')}>Hoàn tất</Button>}</div></div>) : <p className="text-muted mb-0">Chưa có lịch dạy.</p>}</Card.Body></Card></Tab.Pane></Tab.Content></Tab.Container></Container>;
};
export default CoachDashboardPage;
