/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "primary-fixed": "#91f78e",
              "on-surface": "#2c2f2f",
              "on-secondary-fixed": "#004a26",
              "inverse-primary": "#91f78e",
              "on-tertiary-fixed-variant": "#005c64",
              "on-primary": "#d1ffc8",
              "surface-bright": "#f5f7f6",
              "secondary-dim": "#005c30",
              "tertiary-fixed": "#11eaff",
              "surface-container-highest": "#d9dedd",
              "inverse-surface": "#0b0f0f",
              "on-primary-fixed": "#00480f",
              "tertiary": "#00656f",
              "on-secondary": "#ccffd6",
              "surface-tint": "#006b1b",
              "on-secondary-fixed-variant": "#006a38",
              "primary-fixed-dim": "#83e881",
              "on-surface-variant": "#595c5c",
              "surface-container-lowest": "#ffffff",
              "on-primary-container": "#005e17",
              "surface-dim": "#d1d5d4",
              "on-tertiary-container": "#005159",
              "inverse-on-surface": "#9b9d9d",
              "on-background": "#2c2f2f",
              "error-dim": "#b92902",
              "background": "#f5f7f6",
              "primary": "#006b1b",
              "on-tertiary-fixed": "#003d43",
              "secondary-fixed": "#86faac",
              "outline-variant": "#abaead",
              "secondary-fixed-dim": "#77eb9f",
              "on-error-container": "#520c00",
              "on-error": "#ffefec",
              "surface-container-high": "#dfe3e2",
              "outline": "#747777",
              "primary-dim": "#005d16",
              "on-secondary-container": "#005f32",
              "error-container": "#f95630",
              "on-tertiary": "#d4f9ff",
              "tertiary-container": "#11eaff",
              "surface": "#f5f7f6",
              "on-primary-fixed-variant": "#00691a",
              "tertiary-dim": "#005861",
              "surface-variant": "#d9dedd",
              "primary-container": "#91f78e",
              "surface-container": "#e6e9e8",
              "surface-container-low": "#eff1f0",
              "secondary": "#006a38",
              "error": "#b02500",
              "tertiary-fixed-dim": "#00dbee",
              "secondary-container": "#86faac"
      },
      "borderRadius": {
              "DEFAULT": "9999px",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "fontFamily": {
              "heading": ["Instrument Serif", "serif"],
              "body": ["Barlow", "sans-serif"],
              "headline": ["Plus Jakarta Sans"],
              "display": ["Plus Jakarta Sans"],
              "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
